version: '3.4'
services: 
 app:
  build:
   context: .
   dockerfile: Dockerfile
  expose:
   - "5050"
   
 proxy:
  build: 
   context: .
   dockerfile: Dockerfile.nginx
  ports:
   - "8080:8080"
  links:
   - app



